
@host = http://localhost:5000/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODhjNjk4ZWFlYzZkNDFhMmI5YmY4NyIsIm5hbWUiOiJuaXNhbjEiLCJlbWFpbCI6Im5pc2FuMUBvdXRsb29rLmNvbSIsImlhdCI6MTY1MzM3MTU2MSwiZXhwIjoxNjU1OTYzNTYxfQ.ypL9tEWV8Bjycy2qwzU1hwAl2a4-fRS2PtVRP4UHLbg


###
//register
POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "name": "nisan",
    "email": "nisan100@outlook.com",
    "password": "password"
}

###
//login
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "nisan1@outlook.com",
    "password": "password"
}

###
//create job
POST {{host}}/jobs HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

{
    "company": "Turing",
    "position": "Go lang developer"
}

###
//get all jobs
GET {{host}}/jobs HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

{
}

###
//get single job
GET {{host}}/jobs/628dd3a8a5e826795951ab6e HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

{
}

###
//update single job
PATCH {{host}}/jobs/628dd38ad6f097e846d5e2cd HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

{
    "company": "Amazon",
    "position": "Full stack",
    "status": "pending"
}


###
//delete single job
DELETE {{host}}/jobs/628dd38ad6f097e846d5e2cd HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

{
}