
@host = http://localhost:5000/api/v1


###
POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "name": "nisan100",
    "email": "nisan100@outlook.com",
    "password": "password"
}

###
POST {{host}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "nisan100@outlook.com",
    "password": "adminpass"
}